name: frontend

on: [push]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - name: yarn install
        run: yarn install
        working-directory: ./frontend
      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          workdir: frontend/
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: './**/*.{vue,ts,js}'
      - name: Run eslint
        run: yarn lint
        working-directory: ./frontend
